Add apollo package
Add apollo basic configuration

diff --git a/app/project.yml b/app/project.yml
--- a/app/project.yml
+++ b/app/project.yml
@@ -8,6 +8,9 @@ packages:
   Rswift:
     url: https://github.com/mac-cain13/R.swift.Library.git
     from: 5.4.0
+  Apollo:
+    url: https://github.com/apollographql/apollo-ios
+    from: 0.49.1
 settings:
   base:
     MARKETING_VERSION: 1
@@ -153,10 +156,67 @@ targets:
     platform: [iOS, watchOS]
     sources:
       - path: NounsServices
+    dependencies:
+      - package: Apollo
+        product: ApolloWebSocket
     settings:
       base:
         INFOPLIST_FILE:  NounsServices/Info.plist
         PRODUCT_BUNDLE_IDENTIFIER: ca.mohammedibrahim.nounsservices
+    preBuildScripts:
+      - script: |
+                # Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
+                DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"
+
+                while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
+                  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
+                    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
+                    exit 1
+                  fi
+
+                  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
+                done
+
+                # Grab a reference to the directory where scripts are checked out
+                SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"
+
+                if [ -z "${SCRIPT_PATH}" ]; then
+                    echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
+                    exit 1
+                fi
+
+                cd "${SRCROOT}/NounsServices/GraphQL"
+
+                "${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://api.thegraph.com/subgraphs/name/nounsdao/nouns-subgraph"
+        name: Apollo Schema Generation
+      - script: |
+                # Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
+                DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"
+
+                while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
+                  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
+                    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
+                    exit 1
+                  fi
+
+                  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
+                done
+
+                # Grab a reference to the directory where scripts are checked out
+                SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"
+
+                if [ -z "${SCRIPT_PATH}" ]; then
+                    echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
+                    exit 1
+                fi
+
+                cd "${SRCROOT}/NounsServices"
+                "${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="./GraphQL/schema.json" GraphQL/API.swift
+        name: Apollo API Codegen
+        inputFiles:
+          - $SRCROOT/NounsServices/GraphQL/schema.json
+        outputFiles:
+          - $SRCROOT/NounsServices/GraphQL/API.swift
 
 # NounsServices Tests (Framework)
   NounsServices Tests:
